// Include the generated bindings for the CPU implementation. This file is generated by the build script.
include!(concat!(env!("OUT_DIR"), "/myrustllm-cpu-bindings.rs"));

/// A trait for converting a CPU tensor prototype into the CPUTensor interface used by the CPU operations. This is necessary because the CPU operations are implemented in C and expect a specific interface for the tensor data.
pub trait IntoInterface {
    unsafe fn into_interface(&self) -> CPUTensor;
}
